### ISSUE TITLE
API call: cursor position outside buffer

### ISSUE THREAD

**Issue by GopherJ** [fannheyward/coc-rust-analyzer#596] opened 2021-02-02 12:29 UTC
```rust
// 206. 反转链表
// 反转一个单链表。

// 示例:
//
// 输入: 1->2->3->4->5->NULL
// 输出: 5->4->3->2->1->NULL
//
// 进阶:
// 你可以迭代或递归地反转链表。你能否用两种方法解决这道题？
// Definition for singly-linked list.
#[derive(PartialEq, Eq, Clone, Debug)]
pub struct ListNode {
    pub val: i32,
    pub next: Option<Box<ListNode>>,
}

impl ListNode {
    #[inline]
    fn new(val: i32) -> Self {
        ListNode { next: None, val }
    }
}
struct Solution;

impl Solution {
    pub fn reverse_list(head: Option<Box<ListNode>>) -> Option<Box<ListNode>> {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_l206() {
        let mut l1 = ListNode::new(1);
        let mut l2 = ListNode::new(2);
        let mut l3 = ListNode::new(3);
        let mut l4 = ListNode::new(4);
        let mut l5 = ListNode::new(5);

        l4.next = Some(Box::new(l5));
        l3.next = Some(Box::new(l4));
        l2.next = Some(Box::new(l3));
        l1.next = Some(Box::new(l2));

        assert_eq!(
            Solution::reverse_list(Some(Box::new(l1))),
            ListNode {
                val: 5,
                next: Some(Box::new(ListNode {
                    val: 4,
                    next: Some(Box::new(ListNode {
                        val: 3,
                        next: Some(Box::new(ListNode {
                            val: 2,
                            next: Some(Box::new(ListNode { val: 1, next: None }))
                        }))
                    }))
                }))
            } // <---- cursor position,
        );
    }
}
```

**Reproduce**:
![Peek 2021-02-02 20-27](https://user-images.githubusercontent.com/33961674/106600374-48274e00-6595-11eb-876e-148224107486.gif)

**Note**: it's not so easy to reproduce and it took quite some time to be able to reproduce it.

![image](https://user-images.githubusercontent.com/33961674/106600355-42ca0380-6595-11eb-869e-daf5a27b4cf4.png)

**Comment by GopherJ** [comment] 2021-02-02 12:30
I'm not sure if it's a neovim issue

**Comment by fannheyward** [comment] 2021-02-03 02:30
I can't reproduce this issue with latest nvim nightly, have tried many times.

BTW, searching `do_offscreen_popup_nvim` and `populate_floating_win` in GitHub, both are _only_ called in `vim-matchup/matchparen.vim`, maybe this is the point.

Close this for now.

**Closed by fannheyward** 2021-02-03 02:30 UTC

**Comment by GopherJ** [comment] 2021-02-03 05:37
@fannheyward cool I do have matchup, thanks I'll test
