### ISSUE TITLE
Invalid import parsing when import code action was used.

### ISSUE THREAD

**Issue by y-pakorn** [fannheyward/coc-rust-analyzer#934] opened 2022-01-27 16:01 UTC
Invalid import parsing when import code action was used.

Before using auto import,
```rust
use std::io::Result;

fn main() {
    Error;
    println!("Hello, world!");
}

```

After using auto import,

```rust
use std::io{Result, Error}::;

fn main() {
    Error;
    println!("Hello, world!");
}

```

Expected result,

```rust
use std::io::{Error, Result};

fn main() {
    Error;
    println!("Hello, world!");
}
```

**What's the output of `:CocInfo`**
```
## versions

vim version: NVIM v0.6.1
node version: v17.4.0
coc.nvim version: 0.0.80-7ceb6c3404
coc.nvim directory: /Users/----/.vim/plugged/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2022-01-27T22:57:08.561 INFO (pid:73169) [coc-git] - Looking for git in: git
2022-01-27T22:57:08.573 INFO (pid:73169) [services] - registered service "highlight"
2022-01-27T22:57:08.629 INFO (pid:73169) [services] - registered service "rust-analyzer"
2022-01-27T22:57:08.629 INFO (pid:73169) [services] - Rust Analyzer Language Server state change: stopped => starting
2022-01-27T22:57:08.636 INFO (pid:73169) [plugin] - coc.nvim initialized with node: v17.4.0 after 164ms
2022-01-27T22:57:08.656 INFO (pid:73169) [language-client-index] - Language server "rust-analyzer" started with 73175
2022-01-27T22:57:08.696 INFO (pid:73169) [services] - Rust Analyzer Language Server state change: starting => running
2022-01-27T22:57:08.704 INFO (pid:73169) [services] - service rust-analyzer started
2022-01-27T22:57:15.998 INFO (pid:73169) [attach] - receive notification: highlight []
2022-01-27T22:57:17.238 WARN (pid:73169) [plugin] - Slow action "highlight" cost 1240ms
2022-01-27T22:57:17.766 INFO (pid:73169) [attach] - receive notification: codeAction [ 'char' ]
2022-01-27T22:57:20.025 WARN (pid:73169) [plugin] - Slow action "codeAction" cost 2258ms
2022-01-27T22:57:20.576 INFO (pid:73169) [attach] - receive notification: highlight []
2022-01-27T22:57:22.395 INFO (pid:73169) [attach] - receive notification: showInfo []
```

**What's the output of `:CocCommand rust-analyzer.serverVersion`**
```
[coc.nvim] rust-analyzer 17afa2e77 2022-01-24 stable
```

**Comment by fannheyward** [comment] 2022-01-28 02:59
After some debugs, this issue is caused by coc.nvim https://github.com/neoclide/coc.nvim/commit/2c18827ac603841bcac2c540c85620647a007e74

**Comment by fannheyward** [comment] 2022-01-28 03:03
@chemzqm https://github.com/neoclide/coc.nvim/commit/2c18827ac603841bcac2c540c85620647a007e74 broken the `document.applyEdits`.

```
"rust": {
    "command": "rust-analyzer",
    "filetypes": ["rust"],
    "rootPatterns": ["Cargo.toml"]
  }
```

**Comment by fannheyward** [comment] 2022-01-28 10:07
Should be fixed in latest coc.nvim.

**Closed by fannheyward** 2022-01-28 10:07 UTC
Labels: bug

**Comment by y-pakorn** [comment] 2022-01-28 10:14
Thank you ser work perfectly now!
